DROP TABLE IF EXISTS CONTACTS;
DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY (
	CATEGORY_ID INTEGER GENERATED ALWAYS AS IDENTITY,
	CATEGORY_NAME TEXT NOT NULL,
	CREATEAT TIMESTAMP NOT NULL,
	UPDATEAT TIMESTAMP NOT NULL,
	PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE PRODUCT (
	PRODUCT_ID INTEGER GENERATED ALWAYS AS IDENTITY,
	PRODUCT_NAME TEXT NOT NULL,
	CATEGORY_ID INTEGER,
	CREATEAT TIMESTAMP NOT NULL,
	UPDATEAT TIMESTAMP NOT NULL,
	PRIMARY KEY (PRODUCT_ID),
	CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

CREATE TABLE CUSTOMERS(
    CUSTOMER_ID INT GENERATED ALWAYS AS IDENTITY,
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    CREATEAT TIMESTAMP NOT NULL,
    UPDATEAT TIMESTAMP NOT NULL,
    PRIMARY KEY(CUSTOMER_ID)
);

INSERT INTO customers(customer_name)
VALUES('BlueBird Inc'),
      ('Dolphin LLC');	

CREATE TABLE CONTACTS(
    CONTACT_ID INT GENERATED ALWAYS AS IDENTITY,
    CUSTOMER_ID INT,
    CONTACT_NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(15),
    EMAIL VARCHAR(100),
    CREATEAT TIMESTAMP NOT NULL,
    UPDATEAT TIMESTAMP NOT NULL,
    PRIMARY KEY(CONTACT_ID),
    CONSTRAINT FK_CUSTOMER
        FOREIGN KEY(CUSTOMER_ID) 
        REFERENCES CUSTOMERS(CUSTOMER_ID)
);   
	   
INSERT INTO contacts(customer_id, contact_name, phone, email)
VALUES(1,'John Doe','(408)-111-1234','john.doe@bluebird.dev'),
      (1,'Jane Doe','(408)-111-1235','jane.doe@bluebird.dev'),
      (2,'David Wright','(408)-222-1234','david.wright@dolphin.dev');